<a href="https://colab.research.google.com/github/kornkamolp/data-bootcamp-bacth10/blob/main/28_Sep_Numpy_pandas_sklearn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
# from pandas import read_csv

In [5]:
# numpy : numerical python
friends = ["toy", "john", "jame"]

In [6]:
type(friends)

list

In [9]:
arr_friends = np.array(friends) # vector in R

In [10]:
arr_friends[-1]

'jame'

In [11]:
# exam scores
scores = [90, 80, 95, 100,  50]

In [12]:
arr_score = np.array(scores)

In [14]:
np.mean(arr_score)

83.0

In [15]:
np.std(arr_score)

17.776388834631177

In [21]:
# array 2D
twod_list = np.array([
    [1,2,3],
    [4,5,6]
])

In [22]:
twod_list[1,2]

6

In [23]:
# matrix multiplication (dot)

In [26]:
mat1 = np.array([[1,2], [3,4]])
mat2 = np.array([[3,3], [4,5]])

In [27]:
mat1

array([[1, 2],
       [3, 4]])

In [28]:
mat2

array([[3, 3],
       [4, 5]])

In [29]:
mat1.dot(mat2)

array([[11, 13],
       [25, 29]])

In [42]:
# prompt: create a student dataframe with 5 columns. 10 records using pandas

import pandas as pd

# Create a dictionary of student data
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve', 'Frank', 'Grace', 'Heidi', 'Ivan', 'Judy'],
    'Age': [20, 21, 19, 22, 20, 23, 21, 19, 22, 20],
    'Major': ['Computer Science', 'Mathematics', 'Physics', 'Chemistry', 'Biology', 'Engineering', 'Economics', 'Psychology', 'History', 'English'],
    'GPA': [3.8, 3.5, 3.9, 3.2, 3.7, 3.6, 3.4, 3.9, 3.3, 3.8],
    'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix', 'Philadelphia', 'San Antonio', 'San Diego', 'Dallas', 'San Jose']
}

# Create a Pandas DataFrame from the dictionary
df = pd.DataFrame(data)

# Print the DataFrame
print(df)


      Name  Age             Major  GPA          City
0    Alice   20  Computer Science  3.8      New York
1      Bob   21       Mathematics  3.5   Los Angeles
2  Charlie   19           Physics  3.9       Chicago
3    David   22         Chemistry  3.2       Houston
4      Eve   20           Biology  3.7       Phoenix
5    Frank   23       Engineering  3.6  Philadelphia
6    Grace   21         Economics  3.4   San Antonio
7    Heidi   19        Psychology  3.9     San Diego
8     Ivan   22           History  3.3        Dallas
9     Judy   20           English  3.8      San Jose


In [31]:
df["Age"].mean()

20.7

In [34]:
print(df.columns)

Index(['Name', 'Age', 'Major', 'GPA', 'City'], dtype='object')


In [35]:
print(df[["Name", "Major"]])

      Name             Major
0    Alice  Computer Science
1      Bob       Mathematics
2  Charlie           Physics
3    David         Chemistry
4      Eve           Biology
5    Frank       Engineering
6    Grace         Economics
7    Heidi        Psychology
8     Ivan           History
9     Judy           English


In [37]:
df.query("Age > 20") # where clause

Name  Age        Major  GPA          City
1    Bob   21  Mathematics  3.5   Los Angeles
3  David   22    Chemistry  3.2       Houston
5  Frank   23  Engineering  3.6  Philadelphia
6  Grace   21    Economics  3.4   San Antonio
8   Ivan   22      History  3.3        Dallas

In [48]:
df.query("City == 'New York' and GPA > 3.5")[["Name", "Major"]]

Name             Major
0  Alice  Computer Science

In [51]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [59]:
mtcars = pd.read_csv("https://gist.githubusercontent.com/seankross/a412dfbd88b3db70b74b/raw/5f23f993cd87c283ce766e7ac6b329ee7cc2e1d1/mtcars.csv")
mtcars.head()

model   mpg  cyl   disp   hp  drat     wt   qsec  vs  am  gear  \
0          Mazda RX4  21.0    6  160.0  110  3.90  2.620  16.46   0   1     4   
1      Mazda RX4 Wag  21.0    6  160.0  110  3.90  2.875  17.02   0   1     4   
2         Datsun 710  22.8    4  108.0   93  3.85  2.320  18.61   1   1     4   
3     Hornet 4 Drive  21.4    6  258.0  110  3.08  3.215  19.44   1   0     3   
4  Hornet Sportabout  18.7    8  360.0  175  3.15  3.440  17.02   0   0     3   

   carb  
0     4  
1     4  
2     1  
3     1  
4     2

In [62]:
# prepare data
x = mtcars.drop(["model", "mpg"], axis=1) # axis = 0 drop rows , axis = 1 drop columns
y = mtcars["mpg"]

In [63]:
x.head()

cyl   disp   hp  drat     wt   qsec  vs  am  gear  carb
0    6  160.0  110  3.90  2.620  16.46   0   1     4     4
1    6  160.0  110  3.90  2.875  17.02   0   1     4     4
2    4  108.0   93  3.85  2.320  18.61   1   1     4     1
3    6  258.0  110  3.08  3.215  19.44   1   0     3     1
4    8  360.0  175  3.15  3.440  17.02   0   0     3     2

In [64]:
# ml workflow
# 1. split data
# 2. train data
# 3. score
# 4. evaluate

In [67]:
# split data
## set.seed(42)
X_train, X_test, y_train, y_test = train_test_split(
    x, y, test_size = 0.25, random_state = 42 # test size for train 0.75 and test 0.25
)

In [74]:
# train model
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [79]:
# prediction
p = model.predict(X_test)
print(p)

[19.816545   10.98232893 16.31616932 27.16613904 28.59706508 18.29855129
 14.85758111 27.41057736]


In [78]:
# evaluate R-squared
print(model.score(X_test, y_test))
print(model.score(X_train, y_train))

0.7856209608689562
0.8667068951242609
